version: '3'
services:
  domeTattler:
    build:
      context: './domeTattler/'
      dockerfile: Dockerfile
    image: 'ligpibase-dometattler'
    container_name: 'domeTattler'
    user: ${DCUSERID}
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
    volumes:
      - /opt/vc/lib:/opt/vc/lib
      - ${DCDATADIR}/logs/domeTattler/:/home/lig/domeTattler/logs/
      - ${DCDEVDIR}/config/domeTattler.conf:/home/lig/domeTattler/config/domeTattler.conf
      - ${DCDEVDIR}/config/footer.txt:/home/lig/domeTattler/config/footer.txt
    restart: always
    working_dir: /home/lig/domeTattler/
    command: ["python3", "domeTattler.py"]
    networks:
      - ligDockernetPub

  onewireTemps:
    build:
      context: './onewireTemps/'
      dockerfile: Dockerfile
    image: 'ligpibase-onewire'
    container_name: 'onewireTemps'
    user: ${DCUSERID}
    privileged: true
#    devices:
#      - /sys/devices/w1_bus_master1:/sys/devices/w1_bus_master1
    volumes:
      - ${DCDATADIR}/logs/onewireTemps/:/home/lig/onewireTemps/logs/
      - ${DCDEVDIR}/config/dbconfig.conf:/home/lig/onewireTemps/config/dbconfig.conf
    restart: always
    working_dir: /home/lig/onewireTemps/
    command: ["python3", "onewireTemps.py"]
    networks:
      - ligDockernetPub

networks:
    ligDockernetPub:
      external: true
