version: '3'
services:
  gettempLOIS:
    build:
      context: '../submodules/'
      dockerfile: Dockerfile
      args:
        - userid=${DCUSERID}
        - groupid=${DCGRPID}
        - vidid=${VIDID}
        - i2cid=${I2CID}
        - spiid=${SPIID}
        - gpioid=${GPIOID}
    image: 'ligpibase'
    container_name: 'gettempLOIS'
    user: ${DCUSERID}
    volumes:
      - ${DCDATADIR}/logs/mrfreeze/:/home/lig/MrFreeze/logs/
      - ${DCDEVDIR}/config/mrfreeze.conf:/home/lig/MrFreeze/config/mrfreeze.conf
    restart: always
    working_dir: /home/lig/MrFreeze/
    command: ["python3", "Nora.py"]
    networks:
      - ligDockernetPub

  onewireTemps:
    build:
      context: './onewireTemps/'
      dockerfile: Dockerfile
    image: 'ligpibase-onewire'
    container_name: 'onewireTemps'
    user: ${DCUSERID}
    privileged: true
#    devices:
#      - /sys/devices/w1_bus_master1:/sys/devices/w1_bus_master1
    volumes:
      - ${DCDATADIR}/logs/onewireTemps/:/home/lig/onewireTemps/logs/
      - ${DCDEVDIR}/config/dbconfig.conf:/home/lig/onewireTemps/config/dbconfig.conf
    restart: always
    working_dir: /home/lig/onewireTemps/
    command: ["python3", "onewireTemps.py"]
    depends_on:
      - gettempLOIS
    networks:
      - ligDockernetPub

networks:
    ligDockernetPub:
      external: true
