version: '3'
services:
  snapper:
    build:
      context: '../submodules/'
      dockerfile: Dockerfile
      args:
        - userid=${DCUSERID}
        - groupid=${DCGRPID}
        - vidid=${VIDID}
        - i2cid=${I2CID}
        - spiid=${SPIID}
        - gpioid=${GPIOID}
    image: 'ligpibase'
    ports:
      # This one is only needed if using the streamer which
      #   uses the basic python http server
      - 8675:8675
    container_name: 'snapper'
    user: ${DCUSERID}
    devices:
      - /dev/vchiq:/dev/vchiq
      - /dev/vcsm:/dev/vcsm
    volumes:
      - /opt/vc/lib:/opt/vc/lib
      - ${DCDATADIR}/snapper:/home/lig/PiCamHelpers/snaps
      - ${DCDATADIR}/logs/snapper/:/home/lig/PiCamHelpers/logs/
      - ${DCDEVDIR}/config/picamSettings.conf:/home/lig/PiCamHelpers/config/picamSettings.conf
    restart: always
    working_dir: /home/lig/PiCamHelpers/
    command: ["python3", "snapper.py"]
    networks:
      - ligDockernetPub

  nginx:
    build:
      context: '../submodules/'
      dockerfile: Dockerfile_nginxsnapper
      args:
        - nginxver=${NGINX_VERSION}
    image: 'nginx-snapper'
    container_name: nginx-snapper
    ports:
      - 80:80
    volumes:
      - ${DCDEVDIR}/config/index.html:/home/lig/www/index.html
      - ${DCDEVDIR}/config/hancon.js:/home/lig/www/hancon.js
      - ${DCDATADIR}/snapper:/home/lig/www/snaps
      - ${DCDEVDIR}/config/nginx.conf:/etc/nginx/nginx.conf
      - ${DCDEVDIR}/config/nginx-app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - snapper
    restart: always
    networks:
      - ligDockernetPub

networks:
    ligDockernetPub:
      external: true
